@"
sonar.projectKey=GVR
sonar.projectName=GVR Web App
sonar.sources=src
sonar.inclusions=**/*.jsx,**/*.js,**/*.tsx,**/*.ts,**/*.css
sonar.exclusions=node_modules/**,dist/**,.git/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
"@ | Out-File -Encoding utf8 -NoNewline sonar-project.properties
